= Dokumentation Social Game Platform


==	Einführung und Motivation

****
Geplant ist eine Spieleseite die mehrere Spiele beinhaltet, sowohl für Einzelspieler als auch "kompetetive" Spieler in Mehrspieler Modus.

Jeder Teilnehmer soll über ein eigenes Gerät (Bsp. Handy, Laptop, Desktop PC) ohne zusätzliche Installationen mit Standardprogrammen auf die Spiele zugreifen können.
****

== Rahmenbedingungen

****
Im Umfang einer Gruppenarbeit sollte das Projekt im Zeitraum vom 18.10.2022 bis zum 31.12.2022 umgesetzt werden.

Mitwirkende der Gruppe:

* Friedrich Roth (Scrum Master)
* Lukas Michalek (Product Owner)
* Moritz Bartenbach
* Niklas Kausch

Das Projekt wird in einem gemeinsamen GitLab Repository verwaltet.

Die Qualität wird sichergestellt durch einen Reviewprozess.
Alle Veränderungen die den Master betreffen werden von Friedrich Roth überprüft.
Veränderungen von Friedrich Roth werden durch Lukas Michalek überprüft.
Somit ist eine Qualitätssicherung gewährleistet.

Jeder Teilnehmer hatte die Möglichkeit individuell geteilte Aufgaben zu übernehmen, in der Regel wurde jedoch gemeinsam an einem Gerät gearbeitet.

Es wurden Ansätze von SCRUM verwendet, allerdings gab der Projektumfang eine vollständig sinnvolle Nutzung nicht her.
****

== Programmarchitektur

****
Es handelt sich um eine Webanwendung.
Die Anwendung basiert auf dem Client-Server Modell. Eine Kombination aus REST und Websocket sorgt für die Kommunikation zwischen den beiden Instanzen.
Um einen dynamischen Aufbau der Oberfläche zu ermöglichen wurde JavaScript im React Framework eingesetzt. React ermöglicht ein einheitliches Design und einen modularen Aufbau.
Die Logik sowie die Datensätze werden vom Server bereitgestellt, während auf dem Clientsystem die Benutzerschnittstelle, wie vorab erwähnt durch das React Framework, erzeugt und in HTML dargetellt wird.
Die persistente Datenspeicherung erfolgt in Form einer JSON-Datei. Aufgrund der geringen Anforderungen an die Speicheraufgaben wurde sich gegen ein relationales Datenbankmodell entschieden.
Außerdem wurde sich gegen eine Benutzerauthentifizierung entschieden.
Eine direkte Kommunikation zwischen den Clients findet nicht statt. Die Clients synchronisieren sich auf bidirektionalem Weg über den Server, welcher mit JavaScript in NodeJS Framework betrieben wird.

Beispiel hierfür ist das Scoreboard: 

* Initial wird das Scoreboard vom Client über eine HTTP-GET Methode vom Server abgerufen.
* Neue Scores werden per Socket-Nachricht vom Client an den Server gesendet und vom Server verarbeitet.
* Aktualisierungen werden an alle aktiven Clients über eine Socket-Nachricht gesendet.
****